#!/bin/sh

case "$(echo "Shutdown\nRestart\nLogout\nSuspend" | dmenu \
    -b -i -p \
    "Power:" -l 5)" in
        Shutdown) exec sudo shutdown -P now;;
        Restart) exec sudo reboot;;
        Logout) i3 exit;;
        Suspend) sudo zzz;;
esac
